server:
  port: ${PORT:8811}
eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://192.168.1.100:8761/eureka/
  instance:
    hostname: 192.168.1.100
spring:
  application:
    name: cyber-done-chemistry-microservice
    version: @version@
  profiles:
    active: dev
  datasource:
    username: ${CDCS_DB_USERNAME}
    password: ${CDCS_DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${CDCS_DB_URL}
    jpa:
      hibernate:
        ddl-auto: validate
      show-sql: true
  jooq:
    sql-dialect: org.hibernate.dialect.MySQLInnoDBDialect
security:
  jwt-secret: ${JWT_SECRET}
